Fix combined struct definition with variable declaration
Fixes handling of struct definition and variable declaration
of this type, which resulted in

bschubert2@imesrv6 red>spatch --sp-file find_bug.cocci --c++=17 coccinelle_bug_example.cpp
init_defs_builtins: /usr/lib/coccinelle/standard.h
Starting the test...
HANDLING: coccinelle_bug_example.cpp
Fatal error: exception Coccinelle_modules.Common.Impossible(126)

// This struct definition with combined variable declaration fails Coccinelle parsing
struct example : public base_type_t {
    example_struct_t() : base_type_t()
        { }

    void do_something() {
        MYPRINT(0, 0, 0, "Testing %s %d", member1.c_str(), member2);
    }

    std::string member1 = {"test"};
    int member2 = {42};
} global_instance1;  // This form causes Coccinelle to fail

The patch was created wit Augment AI, I'm not familar with
Coccinelle code.

Signed-off-by: Bernd Schubert <bschubert@ddn.com>