Fix: add missing dependency constraint on pyml in the opam file
Reported by kit-ty-kate:
https://github.com/coccinelle/coccinelle/pull/198/commits/3ae8708b342394db1a2f1689774ef9496f0d8c86

With pyml version <20171117, build fails with the following error:
```
File "python/yes_pycocci.ml", line 77, characters 15-46:
 77 |       ~parents:[pycocci_get_class_type parent]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: This expression has type 'a list
        but an expression was expected of type Py.Object.t =
        Pytypes.pyobject
```

Indeed, the signature of `Py.Class.init` (the function which is being
applied here) changed between 20170807 and 20171117. For reference,
the interface was changed by the commit:
https://github.com/thierry-martinez/pyml/commit/2fedb0bc2d27de89668d21760dbc1f90d22f7112