Bug #104: Improve several dependency specifications in make rules
A bit of progress was achieved with one experiment for build script adjustments.
Further changes can be tried out. Unfortunately, an error message like the
following from the program “GNU Make 4.2.1-1.7” was noticed then.
https://systeme.lip6.fr/pipermail/cocci/2017-June/004181.html

…
/usr/bin/ocamlopt.opt …
File "cocci.ml", line 1:
Error: Could not find the .cmi file for interface cocci.mli.
make[3]: *** [Makefile:533: cocci.cmx] Error 2
…


It took then a while to realise how incomplete the dependency specifications
still were which were used so far.
This area is also work in progress (as usual). Several places were improved.

Some extra dependencies were integrated by inclusion of the make script “.depend”
which was automatically generated by the tool “ocamldep”.
Further tests pointed places out despite of this detail where the build approach
failed in a “special” software development configuration.
This approach can still fail occasionally because significant development
efforts and attention are needed to keep the desired build rules consistent.
https://www.gnu.org/software/make/manual/html_node/Multiple-Rules.html


The affected make rules were also repeated in several scripts. They were moved
to a separate script and included then from there.
The relevance of compiled interface descriptions was increased by the adjustment
of corresponding details. Some rules are also automatically generated by
a script like “rule_pair.make” now. The usage of static pattern rules can also
help to some degree.
https://www.gnu.org/software/make/manual/html_node/Static-Usage.html


It is hoped that these working software development results can become another
useful information source for general inspiration and better clarification
of remaining open issues.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>