Pretty-print Failure _ exceptions
On failwith "Error message.", the displayed error message will be
  Error message.
instead of the default OCaml message
  Fatal error: Failure "Error message."